Saving fake_or_real_news.csv to fake_or_real_news (1).csv
Shape: (6335, 4)
Columns: ['id', 'title', 'text', 'label']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      6335 non-null   int64 
 1   title   6335 non-null   object
 2   text    6335 non-null   object
 3   label   6335 non-null   object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB
None
label
REAL    3171
FAKE    3164
Name: count, dtype: int64
Missing values:
 id       0
title    0
text     0
label    0
dtype: int64
Duplicate rows: 0

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
tokenizer_config.json: 100%
 48.0/48.0 [00:00<00:00, 2.32kB/s]
vocab.txt: 100%
 232k/232k [00:00<00:00, 6.65MB/s]
tokenizer.json: 100%
 466k/466k [00:00<00:00, 24.3MB/s]
config.json: 100%
 570/570 [00:00<00:00, 35.5kB/s]
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
model.safetensors: 100%
 440M/440M [00:07<00:00, 74.1MB/s]
All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-5c02042f408e> in <cell line: 0>()
     72 
     73 # Compile Model
---> 74 model.compile(
     75     optimizer=Adam(learning_rate=2e-5),
     76     loss=SparseCategoricalCrossentropy(from_logits=True),

2 frames
/usr/local/lib/python3.11/dist-packages/tensorflow/python/distribute/distribute_lib.py in variable_created_in_scope(self, v)
   4019 
   4020   def variable_created_in_scope(self, v):
-> 4021     return v._distribute_strategy is None  # pylint: disable=protected-access
   4022 
   4023   def _experimental_distribute_dataset(self, dataset, options):

AttributeError: 'Variable' object has no attribute '_distribute_strategy'
